
#line 2 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    /* Note: We specifically omit the test for yy_rule_can_match_eol because it requires
     *       access to the local variable yy_act. Since yyless() is a macro, it would break
     *       existing scanners that call yyless() from OUTSIDE yylex.
     *       One obvious solution it to make yy_act a global. I tried that, and saw
     *       a 5% performance hit in a non-yylineno scanner, because yy_act is
     *       normally declared as a register variable-- so it is not worth it.
     */
    #define  YY_LESS_LINENO(n) \
            do { \
                int yyl;\
                for ( yyl = n; yyl < yyleng; ++yyl )\
                    if ( yytext[yyl] == '\n' )\
                        --yylineno;\
            }while(0)
    #define YY_LINENO_REWIND_TO(dst) \
            do {\
                const char *p;\
                for ( p = yy_cp-1; p >= (dst); --p)\
                    if ( *p == '\n' )\
                        --yylineno;\
            }while(0)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define yywrap() (/*CONSTCOND*/1)
#define YY_SKIP_YYWRAP
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 126
#define YY_END_OF_BUFFER 127
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[364] =
    {   0,
        0,    0,    0,    0,    3,    3,    0,    0,    0,    0,
      127,  125,    1,    1,  110,    7,  102,  117,    6,   29,
       98,   92,   95,  125,  100,   30,   30,  112,  105,   91,
      107,  111,  124,   89,   89,   89,   89,   89,  122,  123,
      114,   89,   89,   89,   89,   89,   89,   89,   89,   89,
       89,   89,   89,   89,   89,   89,   89,  115,  113,   23,
       26,   28,  126,  126,    3,    4,   23,   25,   27,  109,
      103,  118,   99,   93,   94,   96,   97,  121,   33,    2,
        0,  101,   33,   31,    0,    0,    0,   30,  119,  106,
      104,  108,  120,    0,    0,    0,    0,    0,    0,    0,

        0,   89,    0,   33,   88,   89,   89,   89,   89,   89,
       89,   89,   54,   89,   89,   89,   89,   89,   89,   51,
       86,   89,   89,   89,   89,   89,   89,   89,   89,   89,
       89,   89,  116,   16,   17,   20,   21,   18,   19,    9,
       10,   11,   12,   13,   14,   15,   24,    3,    4,    4,
        5,    8,    0,   90,   33,   33,   32,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
       87,   89,   89,   89,   89,   89,   89,   89,   89,   89,
       89,   89,   89,   55,   89,   89,   36,   89,   49,   89,
       89,   89,   89,   89,   89,   89,   89,   89,   89,   89,

       89,   89,   89,   21,   22,    0,    0,    0,   73,    0,
        0,    0,    0,    0,    0,    0,    0,    0,   77,   44,
       89,   57,   43,   89,   89,   89,   89,   89,   89,   52,
       46,   89,   89,   62,   89,   39,   89,   89,   89,   89,
       89,   89,   89,   89,   89,   89,   89,   35,   89,   89,
       21,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,   60,   34,   89,   89,   89,   89,   89,
       89,   37,   89,   89,   89,   40,   89,   89,   89,   89,
       89,   89,   47,   89,   89,   53,   79,   81,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,   78,   89,

       89,   69,   50,   38,   66,   89,   89,   59,   41,   63,
       48,   45,   56,   89,   89,   89,    0,    0,    0,    0,
        0,    0,    0,   76,    0,    0,   89,   58,   68,   89,
       65,   89,   89,   84,   80,    0,    0,   74,    0,    0,
        0,    0,   61,   67,   42,   64,    0,    0,    0,   72,
       82,    0,    0,   70,   75,    0,    0,   85,    0,    0,
        0,   71,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    4,    5,    1,    1,    6,    7,    8,    9,
        9,   10,   11,    9,   12,   13,   14,   15,   16,   16,
       16,   16,   16,   16,   16,   17,   17,   18,    9,   19,
       20,   21,   22,   23,   24,   24,   24,   24,   25,   24,
       26,   26,   26,   26,   26,   27,   26,   28,   29,   26,
       26,   26,   30,   26,   27,   26,   26,   31,   32,   26,
       33,   34,   35,   36,   26,    1,   37,   38,   39,   40,

       41,   42,   43,   44,   45,   26,   46,   47,   48,   49,
       50,   51,   26,   52,   53,   54,   55,   56,   57,   58,
       59,   60,    9,   61,    9,   62,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[63] =
    {   0,
        1,    1,    2,    1,    2,    1,    1,    2,    1,    3,
        1,    1,    1,    1,    4,    4,    4,    1,    1,    1,
        1,    1,    1,    4,    4,    5,    5,    5,    5,    5,
        5,    5,    1,    2,    1,    1,    4,    4,    4,    4,
        4,    4,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        1,    1
    } ;

static const flex_int16_t yy_base[375] =
    {   0,
        0,    0,   60,   61,  471,  470,   67,   68,    0,    0,
      479,  482,  482,  482,  458,  482,  457,  469,  482,  482,
      455,   63,   65,   63,   77,   83,   90,  482,   62,  454,
       68,  482,   81,    0,  101,    0,  444,  447,  482,  482,
      482,  416,  418,   92,   43,  128,   78,  419,   62,  418,
      426,  425,   93,  406,  415,  413,  418,  400,  482,  482,
      482,  482,  482,  182,    0,  138,    0,  482,  482,  482,
      482,  482,  482,  482,  482,  482,  482,  482,  138,  482,
      457,  482,  141,  155,  168,  190,    0,  198,  482,  482,
      482,  482,  482,   72,  400,  409,  412,  111,   75,   51,

      117,    0,  210,  213,    0,  426,  401,  413,  400,  415,
      402,  104,  395,  396,  393,  393,  396,  393,  390,    0,
      110,  394,  385,  119,  391,  131,  151,  395,  388,  147,
      120,  393,  482,  482,  482,  179,  202,  482,  482,  482,
      482,  482,  482,  482,  482,  482,    0,    0,  198,  223,
      482,  482,  434,  482,  226,  229,    0,  382,  398,  385,
      393,  383,  380,  376,  202,  391,  381,  378,  374,  366,
        0,  374,  386,  381,  369,  168,  211,  379,  381,  377,
      369,  375,  378,    0,  364,  366,    0,  369,    0,  366,
      355,  357,  359,  366,  352,  350,  350,  362,  352,  356,

      360,  362,  351,  234,    0,  358,  343,  358,  482,  357,
      346,  351,  335,  336,  342,  347,  333,  336,  482,    0,
      339,    0,    0,  330,  338,  327,  332,  326,  332,    0,
        0,  326,  323,    0,  321,    0,  322,  322,  319,  331,
      321,  325,  330,  329,  327,  317,  322,    0,  310,  322,
      482,  318,  308,  312,  312,  317,  305,  319,  212,  310,
      315,  309,  295,    0,    0,  302,  303,  308,  307,  306,
      297,    0,  305,  290,  294,    0,  302,  299,  301,  285,
      294,  296,    0,  287,  290,    0,  482,  482,  289,  286,
      284,  289,  276,  290,  289,  288,  272,  284,  482,  269,

      269,    0,    0,    0,    0,  281,  280,    0,    0,    0,
        0,    0,    0,  278,  278,  271,  278,  257,  274,  277,
      272,  258,  261,  482,  260,  248,  251,    0,    0,  214,
        0,  225,  223,  482,  482,  214,  222,  482,  219,  212,
      206,  212,    0,    0,    0,    0,  201,  213,  195,  482,
      482,  172,  173,  482,  482,  158,  135,  482,  133,  126,
       84,  482,  482,  267,  272,  277,  282,  284,  289,  294,
      299,  304,   86,   63
    } ;

static const flex_int16_t yy_def[375] =
    {   0,
      363,    1,  364,  364,  365,  365,  366,  366,  367,  367,
      363,  363,  363,  363,  363,  363,  363,  363,  363,  363,
      363,  363,  363,  363,  363,  363,  363,  363,  363,  363,
      363,  363,  363,  368,  368,  368,  368,  368,  363,  363,
      363,  368,  368,  368,  368,  368,  368,  368,  368,  368,
      368,  368,  368,  368,  368,  368,  368,  363,  363,  363,
      363,  363,  363,  363,  369,  370,  371,  363,  363,  363,
      363,  363,  363,  363,  363,  363,  363,  363,  363,  363,
      372,  363,  363,  363,  363,  363,  373,  363,  363,  363,
      363,  363,  363,  363,  363,  363,  363,  363,  363,  363,

      363,  368,  363,  368,  368,  368,  368,  368,  368,  368,
      368,  368,  368,  368,  368,  368,  368,  368,  368,  368,
      368,  368,  368,  368,  368,  368,  368,  368,  368,  368,
      368,  368,  363,  363,  363,  363,  363,  363,  363,  363,
      363,  363,  363,  363,  363,  363,  374,  369,  370,  370,
      363,  363,  372,  363,  363,  363,  373,  363,  363,  363,
      363,  363,  363,  363,  363,  363,  363,  363,  363,  363,
      368,  368,  368,  368,  368,  368,  368,  368,  368,  368,
      368,  368,  368,  368,  368,  368,  368,  368,  368,  368,
      368,  368,  368,  368,  368,  368,  368,  368,  368,  368,

      368,  368,  368,  363,  374,  363,  363,  363,  363,  363,
      363,  363,  363,  363,  363,  363,  363,  363,  363,  368,
      368,  368,  368,  368,  368,  368,  368,  368,  368,  368,
      368,  368,  368,  368,  368,  368,  368,  368,  368,  368,
      368,  368,  368,  368,  368,  368,  368,  368,  368,  368,
      363,  363,  363,  363,  363,  363,  363,  363,  363,  363,
      363,  363,  363,  368,  368,  368,  368,  368,  368,  368,
      368,  368,  368,  368,  368,  368,  368,  368,  368,  368,
      368,  368,  368,  368,  368,  368,  363,  363,  363,  363,
      363,  363,  363,  363,  363,  363,  363,  363,  363,  368,

      368,  368,  368,  368,  368,  368,  368,  368,  368,  368,
      368,  368,  368,  368,  368,  368,  363,  363,  363,  363,
      363,  363,  363,  363,  363,  363,  368,  368,  368,  368,
      368,  368,  368,  363,  363,  363,  363,  363,  363,  363,
      363,  363,  368,  368,  368,  368,  363,  363,  363,  363,
      363,  363,  363,  363,  363,  363,  363,  363,  363,  363,
      363,  363,    0,  363,  363,  363,  363,  363,  363,  363,
      363,  363,  363,  363
    } ;

static const flex_int16_t yy_nxt[545] =
    {   0,
       12,   13,   14,   15,   16,   17,   18,   19,   20,   21,
       22,   23,   24,   25,   26,   27,   27,   28,   29,   30,
       31,   32,   33,   34,   35,   34,   36,   37,   34,   34,
       34,   38,   39,   12,   40,   41,   42,   43,   44,   45,
       46,   47,   48,   34,   49,   34,   50,   34,   51,   34,
       34,   52,   53,   54,   55,   56,   57,   34,   34,   34,
       58,   59,   61,   61,   62,   62,  205,   63,   63,   68,
       68,   63,   63,   74,   69,   69,   76,   79,   79,   79,
       89,   90,   75,  112,   77,   78,   80,   92,   93,  157,
       81,  167,  113,   64,   64,   83,   82,   84,   84,   85,

       64,   64,   83,  120,   88,   88,   88,   86,  158,  168,
      121,  103,  103,   87,   86,  104,  104,  104,  159,   94,
       95,   96,   97,   86,  117,   98,  165,  118,  109,  166,
       86,   99,  362,  100,  101,  110,  125,  126,  103,  103,
       87,  111,  104,  104,  104,  177,  127,  150,  186,  128,
      178,  151,   79,   79,   79,  155,  155,  155,  163,  164,
      169,  190,   86,  187,  201,   86,  202,   83,  170,   84,
       84,   85,  191,  193,  114,  361,  115,  360,   86,   86,
       83,   86,   85,   85,   85,  116,  134,  195,  359,  135,
      194,  199,   86,  204,  204,   86,  136,  137,  358,  200,

      103,  103,  196,  138,  156,  156,  156,  363,   86,  357,
       83,  363,   88,   88,   88,  139,  204,  204,  140,  141,
      224,  225,   86,  142,  156,  156,  156,  104,  104,  104,
      143,  356,  150,  144,  355,  145,  151,  146,   86,  147,
      155,  155,  155,  156,  156,  156,  213,  226,  251,  251,
       86,  214,  294,  354,  353,  227,  352,  351,  350,  349,
      348,  295,  347,  346,  345,  344,   86,   60,   60,   60,
       60,   60,   65,   65,   65,   65,   65,   67,   67,   67,
       67,   67,   63,   63,   63,   63,   63,  102,  102,  148,
      148,  343,  148,  148,  149,  149,  149,  149,  149,  152,

      342,  152,  152,  152,  153,  153,  153,  153,  153,  341,
      340,  339,  338,  337,  336,  335,  334,  333,  332,  331,
      330,  329,  328,  327,  326,  325,  324,  323,  322,  321,
      320,  319,  318,  317,  316,  315,  314,  313,  312,  311,
      310,  309,  308,  307,  306,  305,  304,  303,  302,  301,
      300,  299,  298,  297,  296,  293,  292,  291,  290,  289,
      288,  287,  286,  285,  284,  283,  282,  281,  280,  279,
      278,  277,  276,  275,  274,  273,  272,  271,  270,  269,
      268,  267,  266,  265,  264,  263,  262,  261,  260,  259,
      258,  257,  256,  255,  254,  253,  252,  250,  249,  248,

      247,  246,  245,  244,  243,  242,  241,  240,  239,  238,
      237,  236,  235,  234,  233,  232,  231,  230,  229,  228,
      223,  222,  221,  220,  219,  218,  217,  216,  215,  212,
      211,  210,  209,  208,  207,  206,  154,  203,  198,  197,
      192,  189,  188,  185,  184,  183,  182,  181,  180,  179,
      176,  175,  174,  173,  172,  171,  162,  161,  160,  154,
      133,  132,  131,  130,  129,  124,  123,  122,  119,  108,
      107,  106,  105,   91,   73,   72,   71,   70,  363,   66,
       66,   11,  363,  363,  363,  363,  363,  363,  363,  363,
      363,  363,  363,  363,  363,  363,  363,  363,  363,  363,

      363,  363,  363,  363,  363,  363,  363,  363,  363,  363,
      363,  363,  363,  363,  363,  363,  363,  363,  363,  363,
      363,  363,  363,  363,  363,  363,  363,  363,  363,  363,
      363,  363,  363,  363,  363,  363,  363,  363,  363,  363,
      363,  363,  363,  363
    } ;

static const flex_int16_t yy_chk[545] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    3,    4,    3,    4,  374,    3,    4,    7,
        8,    7,    8,   22,    7,    8,   23,   24,   24,   24,
       29,   29,   22,   45,   23,   23,   25,   31,   31,  373,
       25,  100,   45,    3,    4,   26,   25,   26,   26,   26,

        7,    8,   27,   49,   27,   27,   27,   26,   94,  100,
       49,   35,   35,   26,   27,   35,   35,   35,   94,   33,
       33,   33,   33,   26,   47,   33,   99,   47,   44,   99,
       27,   33,  361,   33,   33,   44,   53,   53,   46,   46,
       26,   44,   46,   46,   46,  112,   53,   66,  121,   53,
      112,   66,   79,   79,   79,   83,   83,   83,   98,   98,
      101,  124,   79,  121,  131,   83,  131,   84,  101,   84,
       84,   84,  124,  126,   46,  360,   46,  359,   79,   84,
       85,   83,   85,   85,   85,   46,   64,  127,  357,   64,
      126,  130,   85,  136,  136,   84,   64,   64,  356,  130,

       86,   86,  127,   64,   86,   86,   86,  149,   85,  353,
       88,  149,   88,   88,   88,   64,  137,  137,   64,   64,
      176,  176,   88,   64,  103,  103,  103,  104,  104,  104,
       64,  352,  150,   64,  349,   64,  150,   64,   88,   64,
      155,  155,  155,  156,  156,  156,  165,  177,  204,  204,
      155,  165,  259,  348,  347,  177,  342,  341,  340,  339,
      337,  259,  336,  333,  332,  330,  155,  364,  364,  364,
      364,  364,  365,  365,  365,  365,  365,  366,  366,  366,
      366,  366,  367,  367,  367,  367,  367,  368,  368,  369,
      369,  327,  369,  369,  370,  370,  370,  370,  370,  371,

      326,  371,  371,  371,  372,  372,  372,  372,  372,  325,
      323,  322,  321,  320,  319,  318,  317,  316,  315,  314,
      307,  306,  301,  300,  298,  297,  296,  295,  294,  293,
      292,  291,  290,  289,  285,  284,  282,  281,  280,  279,
      278,  277,  275,  274,  273,  271,  270,  269,  268,  267,
      266,  263,  262,  261,  260,  258,  257,  256,  255,  254,
      253,  252,  250,  249,  247,  246,  245,  244,  243,  242,
      241,  240,  239,  238,  237,  235,  233,  232,  229,  228,
      227,  226,  225,  224,  221,  218,  217,  216,  215,  214,
      213,  212,  211,  210,  208,  207,  206,  203,  202,  201,

      200,  199,  198,  197,  196,  195,  194,  193,  192,  191,
      190,  188,  186,  185,  183,  182,  181,  180,  179,  178,
      175,  174,  173,  172,  170,  169,  168,  167,  166,  164,
      163,  162,  161,  160,  159,  158,  153,  132,  129,  128,
      125,  123,  122,  119,  118,  117,  116,  115,  114,  113,
      111,  110,  109,  108,  107,  106,   97,   96,   95,   81,
       58,   57,   56,   55,   54,   52,   51,   50,   48,   43,
       42,   38,   37,   30,   21,   18,   17,   15,   11,    6,
        5,  363,  363,  363,  363,  363,  363,  363,  363,  363,
      363,  363,  363,  363,  363,  363,  363,  363,  363,  363,

      363,  363,  363,  363,  363,  363,  363,  363,  363,  363,
      363,  363,  363,  363,  363,  363,  363,  363,  363,  363,
      363,  363,  363,  363,  363,  363,  363,  363,  363,  363,
      363,  363,  363,  363,  363,  363,  363,  363,  363,  363,
      363,  363,  363,  363
    } ;

/* Table of booleans, true if rule could match eol. */
static const flex_int32_t yy_rule_can_match_eol[127] =
    {   0,
1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0,     };

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "objectivec.flex"
#line 2 "objectivec.flex"
	#define YY_NO_UNISTD_H 0
    #include <math.h>
    #include <stdlib.h>
    #include <stdio.h>
    #include <string.h>
    #include <conio.h>
    #include <locale.h>

		
	void addToBuffer( char* buffer, char* str);
	void addToBuffer( char* buffer, char* str, int from, int to);
	void addToBufferOcto( char* buffer,char* str, int line);
	void addToBufferHex( char* buffer,char* str, int line);
	void clearBuffer(char* buffer);
	void endChar(char* buffer, int line);
	void handleToken(char * name, char * value, int startPos);
	void handleToken(char * name, char * value, int startPos, int endPos);
	void handleTokenInt(char * text, int system, int line);
	void handleTokenFloat(char * text, int line);
	void handleChar(char * ch, int startPos);
	void handleTokenKeyword(char * text, int line);
	void handleTokenOperator(char * text, int line);
	void handleError(char * error, int line);


#line 742 "lex.yy.c"

#line 744 "lex.yy.c"

#define INITIAL 0
#define STRING 1
#define MULTILINE_COMMENT 2
#define CHAR 3
#define OCTO_CHAR 4

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif
    
#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput ( int c, char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 54 "objectivec.flex"



#line 58 "objectivec.flex"
	int start = 0;
	char buffer[100000];


#line 974 "lex.yy.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 364 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_current_state != 363 );
		yy_cp = (yy_last_accepting_cpos);
		yy_current_state = (yy_last_accepting_state);

yy_find_action:
		yy_act = yy_accept[yy_current_state];

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER && yy_rule_can_match_eol[yy_act] )
			{
			int yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					
    yylineno++;
;
			}

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
/* rule 1 can match eol */
YY_RULE_SETUP
#line 62 "objectivec.flex"
{}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 64 "objectivec.flex"
{ BEGIN(MULTILINE_COMMENT); start = yylineno; }
	YY_BREAK
case 3:
/* rule 3 can match eol */
YY_RULE_SETUP
#line 65 "objectivec.flex"
{ /*addToBuffer( buffer,yytext); */}
	YY_BREAK
case 4:
/* rule 4 can match eol */
YY_RULE_SETUP
#line 66 "objectivec.flex"
{ /*addToBuffer( buffer,yytext);*/ }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 67 "objectivec.flex"
{ handleToken("multiline comment", "", start, yylineno); BEGIN(INITIAL);}
	YY_BREAK
case YY_STATE_EOF(MULTILINE_COMMENT):
#line 68 "objectivec.flex"
{ BEGIN(INITIAL); handleError("unterminated multiline_comment", start);}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 70 "objectivec.flex"
{BEGIN(CHAR); clearBuffer(buffer);}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 71 "objectivec.flex"
{BEGIN(STRING); clearBuffer(buffer);}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 72 "objectivec.flex"
{BEGIN(INITIAL);handleError("More then one char in \'\'", yylineno);}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 73 "objectivec.flex"
{ addToBuffer( buffer,"\a"); }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 74 "objectivec.flex"
{ addToBuffer( buffer,"\b"); }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 75 "objectivec.flex"
{ addToBuffer( buffer,"\f"); }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 76 "objectivec.flex"
{ addToBuffer( buffer,"\n"); }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 77 "objectivec.flex"
{ addToBuffer( buffer,"\r"); }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 78 "objectivec.flex"
{ addToBuffer( buffer,"\t"); }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 79 "objectivec.flex"
{ addToBuffer( buffer,"\v"); }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 80 "objectivec.flex"
{ addToBuffer( buffer,"\""); }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 81 "objectivec.flex"
{ addToBuffer( buffer,"\'"); }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 82 "objectivec.flex"
{ addToBuffer( buffer,"\?"); }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 83 "objectivec.flex"
{ addToBuffer( buffer,"\\"); }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 84 "objectivec.flex"
{ addToBuffer( buffer,"\0"); }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 85 "objectivec.flex"
{ addToBufferOcto(buffer, yytext+1, yylineno); }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 86 "objectivec.flex"
{ addToBufferHex(buffer, yytext, yylineno);}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 87 "objectivec.flex"
{ addToBuffer( buffer,yytext); }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 88 "objectivec.flex"
{ BEGIN(INITIAL);handleError("Expected hexadecimal number ", yylineno);}
	YY_BREAK
case 25:
/* rule 25 can match eol */
YY_RULE_SETUP
#line 89 "objectivec.flex"
{ BEGIN(INITIAL);handleError("Expected \' ", yylineno); }
	YY_BREAK
case 26:
/* rule 26 can match eol */
YY_RULE_SETUP
#line 90 "objectivec.flex"
{ BEGIN(INITIAL);handleError("Expected \" ", yylineno); }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 91 "objectivec.flex"
{BEGIN(INITIAL);endChar(buffer, yylineno);}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 92 "objectivec.flex"
{ BEGIN(INITIAL);handleToken("string", buffer, yylineno); }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 95 "objectivec.flex"
{handleToken("delimiter", yytext, yylineno); }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 96 "objectivec.flex"
{handleTokenInt(yytext, 10, yylineno);}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 97 "objectivec.flex"
{handleTokenInt(yytext, 8, yylineno);}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 98 "objectivec.flex"
{handleTokenInt(yytext, 16, yylineno);}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 99 "objectivec.flex"
{handleTokenFloat(yytext, yylineno); }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 101 "objectivec.flex"
{handleTokenKeyword( yytext, yylineno);}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 102 "objectivec.flex"
{handleTokenKeyword( yytext, yylineno);}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 103 "objectivec.flex"
{handleTokenKeyword( yytext, yylineno);}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 104 "objectivec.flex"
{handleTokenKeyword( yytext, yylineno);}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 105 "objectivec.flex"
{handleTokenKeyword( yytext, yylineno);}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 106 "objectivec.flex"
{handleTokenKeyword( yytext, yylineno);}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 107 "objectivec.flex"
{handleTokenKeyword( yytext, yylineno);}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 108 "objectivec.flex"
{handleTokenKeyword( yytext, yylineno);}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 109 "objectivec.flex"
{handleTokenKeyword( yytext, yylineno);}
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 110 "objectivec.flex"
{handleTokenKeyword( yytext, yylineno);}
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 111 "objectivec.flex"
{handleTokenKeyword( yytext, yylineno);}
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 113 "objectivec.flex"
{handleTokenKeyword( yytext, yylineno);}
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 114 "objectivec.flex"
{handleTokenKeyword( yytext, yylineno);}
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 115 "objectivec.flex"
{handleTokenKeyword( yytext, yylineno);}
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 117 "objectivec.flex"
{handleTokenKeyword( yytext, yylineno);}
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 119 "objectivec.flex"
{handleTokenKeyword( yytext, yylineno);}
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 120 "objectivec.flex"
{handleTokenKeyword( yytext, yylineno);}
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 122 "objectivec.flex"
{handleTokenKeyword( yytext, yylineno);}
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 123 "objectivec.flex"
{handleTokenKeyword( yytext, yylineno);}
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 125 "objectivec.flex"
{handleTokenKeyword( yytext, yylineno);}
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 126 "objectivec.flex"
{handleTokenKeyword( yytext, yylineno);}
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 128 "objectivec.flex"
{handleTokenKeyword( yytext, yylineno);}
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 130 "objectivec.flex"
{handleTokenKeyword( yytext, yylineno);}
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 131 "objectivec.flex"
{handleTokenKeyword( yytext, yylineno);}
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 132 "objectivec.flex"
{handleTokenKeyword( yytext, yylineno);}
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 134 "objectivec.flex"
{handleTokenKeyword( yytext, yylineno);}
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 135 "objectivec.flex"
{handleTokenKeyword( yytext, yylineno);}
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 136 "objectivec.flex"
{handleTokenKeyword( yytext, yylineno);}
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 137 "objectivec.flex"
{handleTokenKeyword( yytext, yylineno);}
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 139 "objectivec.flex"
{handleTokenKeyword( yytext, yylineno);}
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 140 "objectivec.flex"
{handleTokenKeyword( yytext, yylineno);}
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 141 "objectivec.flex"
{handleTokenKeyword( yytext, yylineno);}
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 142 "objectivec.flex"
{handleTokenKeyword( yytext, yylineno);}
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 143 "objectivec.flex"
{handleTokenKeyword( yytext, yylineno);}
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 144 "objectivec.flex"
{handleTokenKeyword( yytext, yylineno);}
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 145 "objectivec.flex"
{handleTokenKeyword( yytext, yylineno);}
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 147 "objectivec.flex"
{handleTokenKeyword(yytext, yylineno);}
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 148 "objectivec.flex"
{handleTokenKeyword(yytext, yylineno);}
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 149 "objectivec.flex"
{handleTokenKeyword(yytext, yylineno);}
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 150 "objectivec.flex"
{handleTokenKeyword(yytext, yylineno);}
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 152 "objectivec.flex"
{handleTokenKeyword(yytext, yylineno);}
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 153 "objectivec.flex"
{handleTokenKeyword(yytext, yylineno);}
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 154 "objectivec.flex"
{handleTokenKeyword(yytext, yylineno);}
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 156 "objectivec.flex"
{handleTokenKeyword(yytext, yylineno);}
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 157 "objectivec.flex"
{handleTokenKeyword(yytext, yylineno);}
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 158 "objectivec.flex"
{handleTokenKeyword(yytext, yylineno);}
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 159 "objectivec.flex"
{handleTokenKeyword(yytext, yylineno);}
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 162 "objectivec.flex"
{handleTokenKeyword(yytext, yylineno);}
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 163 "objectivec.flex"
{handleTokenKeyword(yytext, yylineno);}
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 164 "objectivec.flex"
{handleTokenKeyword(yytext, yylineno);}
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 165 "objectivec.flex"
{handleTokenKeyword(yytext, yylineno);}
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 166 "objectivec.flex"
{handleTokenKeyword(yytext, yylineno);}
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 168 "objectivec.flex"
{handleTokenKeyword(yytext, yylineno);}
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 171 "objectivec.flex"
{handleToken("constant", "YES", yylineno); }
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 172 "objectivec.flex"
{handleToken("constant", "NO", yylineno); }
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 174 "objectivec.flex"
{handleToken("identifier", yytext, yylineno); }
	YY_BREAK
case 90:
/* rule 90 can match eol */
YY_RULE_SETUP
#line 175 "objectivec.flex"
{handleToken("one_line_comment", "", yylineno); }
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 177 "objectivec.flex"
{handleTokenOperator( yytext, yylineno); }
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 179 "objectivec.flex"
{handleTokenOperator( yytext, yylineno); }
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 180 "objectivec.flex"
{handleTokenOperator( yytext, yylineno); }
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 181 "objectivec.flex"
{handleTokenOperator( yytext, yylineno); }
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 182 "objectivec.flex"
{handleTokenOperator( yytext, yylineno); }
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 183 "objectivec.flex"
{handleTokenOperator( yytext, yylineno); }
	YY_BREAK
case 97:
YY_RULE_SETUP
#line 184 "objectivec.flex"
{handleTokenOperator( yytext, yylineno); }
	YY_BREAK
case 98:
YY_RULE_SETUP
#line 185 "objectivec.flex"
{handleTokenOperator( yytext, yylineno); }
	YY_BREAK
case 99:
YY_RULE_SETUP
#line 186 "objectivec.flex"
{handleTokenOperator( yytext, yylineno); }
	YY_BREAK
case 100:
YY_RULE_SETUP
#line 187 "objectivec.flex"
{handleTokenOperator( yytext, yylineno); }
	YY_BREAK
case 101:
YY_RULE_SETUP
#line 188 "objectivec.flex"
{handleTokenOperator( yytext, yylineno); }
	YY_BREAK
case 102:
YY_RULE_SETUP
#line 189 "objectivec.flex"
{handleTokenOperator( yytext, yylineno); }
	YY_BREAK
case 103:
YY_RULE_SETUP
#line 190 "objectivec.flex"
{handleTokenOperator( yytext, yylineno); }
	YY_BREAK
case 104:
YY_RULE_SETUP
#line 193 "objectivec.flex"
{handleTokenOperator( yytext, yylineno); }
	YY_BREAK
case 105:
YY_RULE_SETUP
#line 194 "objectivec.flex"
{handleTokenOperator( yytext, yylineno); }
	YY_BREAK
case 106:
YY_RULE_SETUP
#line 195 "objectivec.flex"
{handleTokenOperator( yytext, yylineno); }
	YY_BREAK
case 107:
YY_RULE_SETUP
#line 196 "objectivec.flex"
{handleTokenOperator( yytext, yylineno); }
	YY_BREAK
case 108:
YY_RULE_SETUP
#line 197 "objectivec.flex"
{handleTokenOperator( yytext, yylineno); }
	YY_BREAK
case 109:
YY_RULE_SETUP
#line 198 "objectivec.flex"
{handleTokenOperator( yytext, yylineno); }
	YY_BREAK
case 110:
YY_RULE_SETUP
#line 199 "objectivec.flex"
{handleTokenOperator( yytext, yylineno); }
	YY_BREAK
case 111:
YY_RULE_SETUP
#line 200 "objectivec.flex"
{handleTokenOperator( yytext, yylineno); }
	YY_BREAK
case 112:
YY_RULE_SETUP
#line 201 "objectivec.flex"
{handleTokenOperator( yytext, yylineno); }
	YY_BREAK
case 113:
YY_RULE_SETUP
#line 203 "objectivec.flex"
{handleTokenOperator( yytext, yylineno); }
	YY_BREAK
case 114:
YY_RULE_SETUP
#line 204 "objectivec.flex"
{handleTokenOperator( yytext, yylineno); }
	YY_BREAK
case 115:
YY_RULE_SETUP
#line 205 "objectivec.flex"
{handleTokenOperator( yytext, yylineno); }
	YY_BREAK
case 116:
YY_RULE_SETUP
#line 206 "objectivec.flex"
{handleTokenOperator( yytext, yylineno); }
	YY_BREAK
case 117:
YY_RULE_SETUP
#line 207 "objectivec.flex"
{handleTokenOperator( yytext, yylineno); }
	YY_BREAK
case 118:
YY_RULE_SETUP
#line 208 "objectivec.flex"
{handleTokenOperator( yytext, yylineno); }
	YY_BREAK
case 119:
YY_RULE_SETUP
#line 210 "objectivec.flex"
{handleTokenOperator( yytext, yylineno); }
	YY_BREAK
case 120:
YY_RULE_SETUP
#line 211 "objectivec.flex"
{handleTokenOperator( yytext, yylineno); }
	YY_BREAK
case 121:
YY_RULE_SETUP
#line 213 "objectivec.flex"
{handleTokenOperator( yytext, yylineno); }
	YY_BREAK
case 122:
YY_RULE_SETUP
#line 215 "objectivec.flex"
{handleTokenOperator( yytext, yylineno); }
	YY_BREAK
case 123:
YY_RULE_SETUP
#line 216 "objectivec.flex"
{handleTokenOperator( yytext, yylineno); }
	YY_BREAK
case 124:
YY_RULE_SETUP
#line 218 "objectivec.flex"
{handleToken("string modifier", yytext, yylineno); }
	YY_BREAK
case 125:
YY_RULE_SETUP
#line 220 "objectivec.flex"
{handleToken("unknown character", yytext, yylineno); }
	YY_BREAK
case 126:
YY_RULE_SETUP
#line 221 "objectivec.flex"
ECHO;
	YY_BREAK
#line 1677 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(STRING):
case YY_STATE_EOF(CHAR):
case YY_STATE_EOF(OCTO_CHAR):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_last_accepting_cpos);
				yy_current_state = (yy_last_accepting_state);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 364 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 364 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 363);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

    if ( c == '\n' ){
        --yylineno;
    }

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	if ( c == '\n' )
		
    yylineno++;
;

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    /* We do not touch yylineno unless the option is enabled. */
    yylineno =  1;
    
    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 221 "objectivec.flex"


void addToBuffer( char* buffer, char* str){
	strcat(buffer, str);
}

void addToBufferOcto( char* buffer, char* str, int line){
	int num = strtol(str, NULL, 8);
	if ( num > 255){
		handleError("too big number for char", line);
	}
	else {
		char sub[2];
		sub[0] = (char)num;
		sub[1] = 0;
		strcat(buffer, sub);
	}
}

void addToBufferHex( char* buffer, char* str, int line){
	char * buf = (char *)malloc(strlen(str));
	strcpy(buf, str);
	buf[0] = '0';
	int num = strtol(buf, NULL, 16);
	//printf("Hex found: %d from str: %s handled str: %s\n", num, str,buf);
	if ( num > 255){
		handleError("too big number for char", line);
	}
	else {
		char sub[2];
		sub[0] = (char)num;
		sub[1] = 0;
		strcat(buffer, sub);
	}
}


void clearBuffer(char* buffer){
	buffer[0] = 0;
}

void endChar(char* buffer, int line){
	if ( strlen(buffer) == 0){
		handleError("Empty char",line);
	} else {
		handleToken("char", buffer, line);
	}
}
	
void handleToken(char * name, char * value, int startPos){
	printf("Found: %s at line %d \nvalue: %s\n\n", name, startPos, value);
} 

void handleToken(char * name, char * value, int startPos, int endPos){
	printf("Found: %s from line %d to line %d \nvalue: %s\n\n", name, startPos, endPos, value);
} 

void handleTokenInt(char * text, int system, int line) {
	char numstr[40];
	int num = strtol(text, NULL, system);
	itoa(num, numstr, 10);
	handleToken("int number", numstr, line);
}

void handleTokenFloat(char * text, int line) {
	
	char * loc = setlocale(LC_ALL,NULL);
	setlocale(LC_ALL,"C");
	double number = atof(text);
	char numstr[50] = "";
	sprintf(numstr, "%0.10lf", number);
	handleToken("float number", numstr, line);
	
	setlocale(LC_ALL, loc);
	
}

void handleTokenKeyword(char * text, int line){
	handleToken("keyword", text, line);
}

void handleTokenOperator(char * text, int line){
	handleToken("operator", text, line);
}

void handleError(char * error, int line){
	printf("Error at line %d: %s\n\n",line, error);
} 



